/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package boboyuks.Payment;

import java.util.List;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Nugraha Adhitama
 */
public class PaymentPopup extends javax.swing.JFrame {
    private String bankName;
    private Payment paymentInstance;
    /**
     * Creates new form PaymentPopup
     */
    public PaymentPopup() {
        initComponents();
    }

    PaymentPopup(String bankName, List<String> randomNumbers, String[] bankNumbers, Payment paymentInstance) {
        this();
        this.bankName = bankName;
        this.paymentInstance = paymentInstance;
        setBankName(bankName);
        setVirtualAccountNumber(generateRandomDigits(), bankNumbers);
    }

    
    private void setBankName(String bankName) {
        choosenBank.setText(bankName);
    }
    
    private void setVirtualAccountNumber(String randomDigits, String[] bankNumbers) {
        String bankCode = getBankCode(bankName, bankNumbers);
        numberVA.setText(bankCode + randomDigits); // Append fixed bank code to random digits
    }

    
    private String getBankCode(String bankName, String[] bankNumbers) {
        switch (bankName) {
            case "BCA VIRTUAL ACCOUNT":
                return bankNumbers[0];
            case "MANDIRI VIRTUAL ACCOUNT":
                return bankNumbers[1];
            case "BNI VIRTUAL ACCOUNT":
                return bankNumbers[2];
            case "BRI VIRTUAL ACCOUNT":
                return bankNumbers[3];
            case "BSI VIRTUAL ACCOUNT":
                return bankNumbers[4];
            default:
                return "";
        }
    }

    
    private String generateRandomDigits() {
        Random random = new Random();
        return String.format("%010d", random.nextInt(1000000000));
    }
    
    public void setPaymentInstance(Payment paymentInstance) {
        this.paymentInstance = paymentInstance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        choosenBank = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        numberVA = new javax.swing.JLabel();
        finishBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(220, 240, 255));

        jLabel1.setFont(new java.awt.Font("Eras Bold ITC", 1, 45)); // NOI18N
        jLabel1.setText("Bank Transfer");

        choosenBank.setFont(new java.awt.Font("Eras Medium ITC", 0, 35)); // NOI18N
        choosenBank.setText("Bank Virtual Account");

        jLabel3.setFont(new java.awt.Font("Eras Bold ITC", 1, 35)); // NOI18N
        jLabel3.setText("Rp. 620.293");

        jLabel4.setFont(new java.awt.Font("Eras Medium ITC", 0, 35)); // NOI18N
        jLabel4.setText("Total Price");

        numberVA.setFont(new java.awt.Font("Eras Bold ITC", 1, 35)); // NOI18N
        numberVA.setText("XXXXXXXXXXXXX");

        finishBtn.setBackground(new java.awt.Color(89, 185, 255));
        finishBtn.setFont(new java.awt.Font("Eras Bold ITC", 1, 30)); // NOI18N
        finishBtn.setForeground(new java.awt.Color(255, 255, 255));
        finishBtn.setText("I FINISHED THE PAYMENT");
        finishBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(choosenBank))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(finishBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(numberVA)))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(choosenBank)
                .addGap(36, 36, 36)
                .addComponent(numberVA)
                .addGap(47, 47, 47)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(100, 100, 100)
                .addComponent(finishBtn)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void finishBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishBtnActionPerformed
        int idReservation = 1; // Sesuaikan logika untuk mendapatkan ID reservasi yang sebenarnya
        paymentInstance.handlePaymentPaid(idReservation);
    }//GEN-LAST:event_finishBtnActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaymentPopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaymentPopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaymentPopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaymentPopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaymentPopup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel choosenBank;
    private javax.swing.JButton finishBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel numberVA;
    // End of variables declaration//GEN-END:variables

}
