package boboyuks.BookingHotel;


import boboyuks.ReviewOrder.ReviewOrder;
import java.sql.DriverManager;
import java.sql.Statement;
import java.text.NumberFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Locale;
import java.util.concurrent.TimeUnit;
import java.util.regex.Pattern;

/**
 *
 * @author Nugraha Adhitama
 */
public class BookingHotel extends javax.swing.JFrame {

    // Format ttanggal dari JDateChooser
    private SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    
    private int durationOfStay;
    
    /**
     * Creates new form BookingHotel
     */
    public BookingHotel() {
        int roomAmount = Integer.parseInt(storage.SessionStorage.bookedHotelData.get("room_amount"));
        int roomPrice = Integer.parseInt(storage.SessionStorage.bookedHotelData.get("roomPrice"));
        
        initComponents();
        
        // Tampilkan checkin date bila dimasukkan sebelum nya
        String checkinDateGlobal = storage.SessionStorage.bookedHotelData.get("checkin_date");
        if (checkinDateGlobal != null) {
            try {
                Calendar calendar = Calendar.getInstance();
                calendar.setTime(dateFormat.parse(checkinDateGlobal));
                checkInDate.setCalendar(calendar);
            } catch (Exception e) {}
        }
        
        // Tampilkan checkout date bila dimasukkan sebelum nya
        String checkoutDateGlobal = storage.SessionStorage.bookedHotelData.get("checkout_date");
        if (checkinDateGlobal != null) {
            try {
                Calendar calendar = Calendar.getInstance();
                calendar.setTime(dateFormat.parse(checkoutDateGlobal));
                checkOutDate.setCalendar(calendar);
            } catch (Exception e) {}
        }
        
        try {
            Date checkIn = dateFormat.parse(checkinDateGlobal);
            Date checkOut = dateFormat.parse(checkoutDateGlobal);
            
            long duration = checkOut.getTime() - checkIn.getTime();
            long daysBetween = TimeUnit.DAYS.convert(duration, TimeUnit.MILLISECONDS);
            
            durationOfStay = (int) daysBetween;
        } catch(Exception e) {System.out.println(e);}
        
        textHotelName.setText(storage.SessionStorage.bookedHotelData.get("name"));
        textHotelRoomNameDetail.setText(
                "(" + roomAmount + "x) "
                + storage.SessionStorage.bookedHotelData.get("roomName")
                + " " + durationOfStay + " Night(s)"
        );
        
        Locale myIndonesianLocale = new Locale("in", "ID");
        NumberFormat formatRupiah = NumberFormat.getCurrencyInstance(myIndonesianLocale);
        
        
        roomPrice = roomPrice * roomAmount * durationOfStay;
        int taxes = (int) Math.round(roomPrice * 0.13);
        int totalPrice = roomPrice + taxes;
        textHotelRoomPrice.setText(formatRupiah.format(roomPrice));
        textTaxes.setText(formatRupiah.format(taxes));
        
        String totalPriceStr = formatRupiah.format(totalPrice);
        textTotalRoomPrice.setText(totalPriceStr);
        
        // simpan total harga
        storage.SessionStorage.bookedHotelData.put("totalPriceStr", totalPriceStr);
        storage.SessionStorage.bookedHotelData.put("totalPrice", Integer.toString(totalPrice));
        
        textGuestPerRoom.setText(
                storage.SessionStorage.bookedHotelData.get("guest_per_room")
                + " Adults"
        );
    }
    
    private boolean isValidEmail(String email) {
        String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$";
        Pattern pattern = Pattern.compile(emailRegex);
            if (email == null)
                return false;
            return pattern.matcher(email).matches();
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        phoneNumber = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        emailAddress = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        textTotalRoomPrice = new javax.swing.JLabel();
        textHotelRoomPrice = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        textHotelRoomNameDetail = new javax.swing.JTextPane();
        jLabel13 = new javax.swing.JLabel();
        textTaxes = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        textHotelName = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        textHotelRoomName = new javax.swing.JTextPane();
        jLabel19 = new javax.swing.JLabel();
        textBedType = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        textGuestPerRoom = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        textFacilities = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        checkInDate = new com.toedter.calendar.JDateChooser();
        checkOutDate = new com.toedter.calendar.JDateChooser();
        jLabel15 = new javax.swing.JLabel();
        GoToReviewButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(16, 125, 205));

        jLabel1.setFont(new java.awt.Font("Eras Bold ITC", 1, 47)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BOBOYUKS");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Inbox");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("My Order");

        jButton1.setBackground(new java.awt.Color(89, 185, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("My Account");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 225, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(52, 52, 52)
                .addComponent(jLabel3)
                .addGap(58, 58, 58)
                .addComponent(jButton1)
                .addGap(46, 46, 46))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(jButton1))
                    .addComponent(jLabel1))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Eras Bold ITC", 1, 50)); // NOI18N
        jLabel4.setText("Hotel Booking");

        jLabel5.setFont(new java.awt.Font("Eras Medium ITC", 0, 30)); // NOI18N
        jLabel5.setText("Order Detail:");

        jPanel1.setBackground(new java.awt.Color(89, 185, 255));

        jLabel6.setFont(new java.awt.Font("Eras Medium ITC", 0, 28)); // NOI18N
        jLabel6.setText("Full Name:");

        fname.setFont(new java.awt.Font("Eras Medium ITC", 0, 20)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Eras Medium ITC", 0, 28)); // NOI18N
        jLabel7.setText("Phone:");

        phoneNumber.setFont(new java.awt.Font("Eras Medium ITC", 0, 20)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Eras Medium ITC", 0, 28)); // NOI18N
        jLabel8.setText("Email:");

        emailAddress.setFont(new java.awt.Font("Eras Medium ITC", 0, 20)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(phoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(32, 32, 32)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(emailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(emailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(phoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Eras Medium ITC", 0, 30)); // NOI18N
        jLabel9.setText("Price Detail : ");

        jPanel4.setBackground(new java.awt.Color(89, 185, 255));

        jLabel10.setFont(new java.awt.Font("Eras Bold ITC", 1, 28)); // NOI18N
        jLabel10.setText("Total");

        textTotalRoomPrice.setFont(new java.awt.Font("Eras Bold ITC", 1, 28)); // NOI18N
        textTotalRoomPrice.setText("Rp. 620.293");

        textHotelRoomPrice.setFont(new java.awt.Font("Eras Medium ITC", 0, 28)); // NOI18N
        textHotelRoomPrice.setText("Rp. 550.000");

        textHotelRoomNameDetail.setBackground(new java.awt.Color(89, 185, 255));
        textHotelRoomNameDetail.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        textHotelRoomNameDetail.setText("(1x)Superior Tropical Twin Beds Room 1 Night");
        jScrollPane3.setViewportView(textHotelRoomNameDetail);

        jLabel13.setFont(new java.awt.Font("Eras Medium ITC", 0, 28)); // NOI18N
        jLabel13.setText("Taxes and Fees (13%)");

        textTaxes.setFont(new java.awt.Font("Eras Medium ITC", 0, 28)); // NOI18N
        textTaxes.setText("Rp. 70.293");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textTotalRoomPrice)
                    .addComponent(textHotelRoomPrice)
                    .addComponent(textTaxes))
                .addGap(28, 28, 28))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(textTotalRoomPrice))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(textHotelRoomPrice)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(textTaxes))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(89, 185, 255));

        textHotelName.setFont(new java.awt.Font("Eras Medium ITC", 0, 28)); // NOI18N
        textHotelName.setText("Malaka Hotel Bandung");

        jLabel17.setFont(new java.awt.Font("Eras Medium ITC", 0, 25)); // NOI18N
        jLabel17.setText("Check-In");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        jLabel18.setText("Check-Out");

        textHotelRoomName.setBackground(new java.awt.Color(89, 185, 255));
        textHotelRoomName.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        textHotelRoomName.setText("(1x) Superior Tropical Twin Beds Room");
        jScrollPane4.setViewportView(textHotelRoomName);

        jLabel19.setFont(new java.awt.Font("Eras Medium ITC", 0, 25)); // NOI18N
        jLabel19.setText("Guest per Room");

        textBedType.setFont(new java.awt.Font("Eras Medium ITC", 0, 25)); // NOI18N
        textBedType.setText("Twin Bed");

        jLabel21.setFont(new java.awt.Font("Eras Medium ITC", 0, 25)); // NOI18N
        jLabel21.setText("Bed Type");

        textGuestPerRoom.setFont(new java.awt.Font("Eras Medium ITC", 0, 25)); // NOI18N
        textGuestPerRoom.setText("2 Adults");

        jLabel23.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://i.postimg.cc/prFxXVfy/blake-woolwine-3mlg5-BRUif-M-unsplash.jpg")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());

        jLabel24.setFont(new java.awt.Font("Eras Medium ITC", 0, 24)); // NOI18N
        jLabel24.setText("Facilities");

        textFacilities.setFont(new java.awt.Font("Eras Medium ITC", 0, 22)); // NOI18N
        textFacilities.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://i.postimg.cc/c4jG4vzF/material-symbols-wifi.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        textFacilities.setText("Wifi");

        jLabel26.setFont(new java.awt.Font("Eras Medium ITC", 0, 22)); // NOI18N
        jLabel26.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://i.postimg.cc/wMpckQ3w/Vector-1.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        jLabel26.setText("Breakfast");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(textFacilities)
                            .addComponent(jLabel26)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textHotelName)
                            .addComponent(jLabel17)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(checkInDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel18)
                                        .addComponent(checkOutDate, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel19))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(textBedType)
                                    .addComponent(textGuestPerRoom))))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(textHotelName)
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkInDate, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkOutDate, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(textGuestPerRoom))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(textBedType))
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(18, 18, 18)
                        .addComponent(textFacilities)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel26)))
                .addContainerGap(140, Short.MAX_VALUE))
        );

        jLabel15.setFont(new java.awt.Font("Eras Medium ITC", 0, 30)); // NOI18N
        jLabel15.setText("Contact Detail :");

        GoToReviewButton.setBackground(new java.awt.Color(89, 185, 255));
        GoToReviewButton.setFont(new java.awt.Font("Eras Bold ITC", 1, 30)); // NOI18N
        GoToReviewButton.setForeground(new java.awt.Color(255, 255, 255));
        GoToReviewButton.setText("CONTINUE TO REVIEW");
        GoToReviewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoToReviewButtonActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jPanel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel15, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(GoToReviewButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(GoToReviewButton)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(33, 33, 33)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 133, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(43, 43, 43)
                    .addComponent(jLabel15)
                    .addContainerGap(954, Short.MAX_VALUE)))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(24, 24, 24)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(GoToReviewButton)
                .addGap(0, 567, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(225, 225, 225)
                    .addComponent(jLabel15)
                    .addContainerGap(1553, Short.MAX_VALUE)))
        );

        jScrollPane1.setViewportView(jLayeredPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1284, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GoToReviewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoToReviewButtonActionPerformed
        // TODO add your handling code here:
        
        Date checkIn = checkInDate.getDate();
        Date checkOut = checkOutDate.getDate();
        
        String checkInDateStr = dateFormat.format(checkIn);
        String checkOutDateStr = dateFormat.format(checkOut);
        String fullNameInput = fname.getText();
        String phoneNumberInput = phoneNumber.getText();
        String emailAddressInput = emailAddress.getText();
        
        // Validasi apakah tanggal telah dipilih
        if (checkIn == null) {
            JOptionPane.showMessageDialog(this, "Please select a check-in date.", "Missing Information", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (checkOut == null) {
            JOptionPane.showMessageDialog(this, "Please select a check-out date.", "Missing Information", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // validasi nama lenkgap
        if (fullNameInput.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your full name.", "Missing Information", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // validasi nomor telpon
        if (phoneNumberInput.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your phone number.", "Missing Information", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // validasi email
        if (emailAddressInput.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your email.", "Missing Information", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (!isValidEmail(emailAddressInput)) {
            JOptionPane.showMessageDialog(this, "Please enter a valid email.", "Invalid Email", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // validasi tanggal checkout tidak sebelum tanggal checkin
        if (!checkOut.after(checkIn)) {
            JOptionPane.showMessageDialog(this, "Check-out date must be after check-in date.", "Date invalid", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        storage.SessionStorage.bookedHotelData.put("userFullname", fullNameInput);
        storage.SessionStorage.bookedHotelData.put("userPhoneNumber", phoneNumberInput);
        storage.SessionStorage.bookedHotelData.put("userEmail", emailAddressInput);

        ReviewOrder reviewOrder = new ReviewOrder(checkInDateStr, checkOutDateStr, fullNameInput, phoneNumberInput, emailAddressInput);
        reviewOrder.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_GoToReviewButtonActionPerformed

    /**
     * @param args  the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookingHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookingHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookingHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookingHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookingHotel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GoToReviewButton;
    private com.toedter.calendar.JDateChooser checkInDate;
    private com.toedter.calendar.JDateChooser checkOutDate;
    private javax.swing.JTextField emailAddress;
    private javax.swing.JTextField fname;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField phoneNumber;
    private javax.swing.JLabel textBedType;
    private javax.swing.JLabel textFacilities;
    private javax.swing.JLabel textGuestPerRoom;
    private javax.swing.JLabel textHotelName;
    private javax.swing.JTextPane textHotelRoomName;
    private javax.swing.JTextPane textHotelRoomNameDetail;
    private javax.swing.JLabel textHotelRoomPrice;
    private javax.swing.JLabel textTaxes;
    private javax.swing.JLabel textTotalRoomPrice;
    // End of variables declaration//GEN-END:variables
}
